language: go

go:
  - 1.8.x
  - tip

script:
  - go test .\chapter-2-creational-patterns\singleton\ -race -coverprofile=coverage.txt -covermode=atomic
  - go test .\chapter-9-concurrency-patterns\barrier\ -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)  