language: go

go:
  - 1.8.x
  - tip

before_script:
  - chmod +x ./scripts/run-tests-coverage.sh  

script: ./scripts/run-tests-coverage.sh
  
after_success:
  - bash <(curl -s https://codecov.io/bash)